spring.config.activate.on-profile: prod

server:
  port: 5000
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://symbiocreation.auth0.com/
          audiences: rid6ZPjGfNTsGKlDGkQX97ECXJxLuzYa

#spring.datasource.url: connection string # to be changed
#spring.datasource.username: theusername # to be changed
#spring.datasource.password: thepassword # to be changed

spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers: true

fablat.ui.uri: https://app.fab.lat

logging:
  level:
    root: INFO
#    org.springframework.web: ERROR
#    org.springframework.security: DEBUG
#    com.auth0.example: TRACE